### ISSUE TITLE
Why not convert all words to lowercase

### ISSUE THREAD

**Issue by hailiang-wang** [eyaler/word2vec-slim#2]
The current vocab set is **299567**, but when convert the words into lowercase, there is **179193** unique words. 

So, why there are so many duplicated words?
For example, both of **kittrell** and **KITTRELL** are in vocab.

This confused me when using the vectors.
Why not convert all words into lowercase?

**Comment by eyaler** [comment]
In the final model we get:
total: 299567
all lower case: 111441
first upper case: 134047
all upper case: 46639
mixed case: 7440

specifically for words with duplicate instances we get:
total: 207817
all lower case: 72878
first upper case: 85999
all upper case: 42682
mixed case: 6258

AFAIAC in general one would like to retain the semantics embodied in the letter case. Specifically, a capitalized first letter in English usually implies that a noun is a proper name, and all caps usually implies an acronym. For example: apple and Apple may have different meanings. For performance purposes I don't find it critical to reduce the "duplicate" words. Alternatively, in your use-case you may indeed want to lower case, strip, etc.

**Comment by hailiang-wang** [comment]
Thanks. 👍
